using EF_DietaryProject.Entities.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EF_DietaryProject.DAL.SeedData;

public class FoodSeedData : IEntityTypeConfiguration<Food>
{
    public void Configure(EntityTypeBuilder<Food> builder)
    {
        builder.HasData(
                new Food { Id = 1, FoodName = "Grilled chicken", CaloryPerGram = 1.19f, PhotoPath = ".\\Images\\Grilled Chicken.jpg" },
                new Food { Id = 2, FoodName = "Steak", CaloryPerGram = 2.89f, PhotoPath = ".\\Images\\Steak.jpg" },
                new Food { Id = 3, FoodName = "Salmon", CaloryPerGram = 2.19f, PhotoPath = ".\\Images\\Salmon.jpg" },
                new Food { Id = 4, FoodName = "Tuna", CaloryPerGram = 1.29f, PhotoPath = ".\\Images\\Tuna.jpg" },
                new Food { Id = 5, FoodName = "Cod", CaloryPerGram = 0.89f, PhotoPath = ".\\Images\\Cod.jpg" },
                new Food { Id = 6, FoodName = "Shrimp", CaloryPerGram = 1.99f, PhotoPath = ".\\Images\\Shrimp.jpg" },
                new Food { Id = 7, FoodName = "Beef stir-fry", CaloryPerGram = 1.79f, PhotoPath = ".\\Images\\Beef stir-fry.jpg" },
                new Food { Id = 8, FoodName = "Chicken fajitas", CaloryPerGram = 1.39f, PhotoPath = ".\\Images\\Chicken fajitas.jpg" },
                new Food { Id = 9, FoodName = "Meatloaf", CaloryPerGram = 2.09f, PhotoPath = ".\\Images\\Meatloaf.jpg" },
                new Food { Id = 10, FoodName = "Grilled fish", CaloryPerGram = 1.59f, PhotoPath = ".\\Images\\Grilled fish.jpg" },
                new Food { Id = 11, FoodName = "Pork chops", CaloryPerGram = 2.49f, PhotoPath = ".\\Images\\Pork chops.jpg" },
                new Food { Id = 12, FoodName = "Chicken parmesan", CaloryPerGram = 2.29f, PhotoPath = ".\\Images\\Chicken parmesan.jpg" },
                new Food { Id = 13, FoodName = "Beef stew", CaloryPerGram = 1.89f, PhotoPath = ".\\Images\\Beef stew.jpg" },
                new Food { Id = 14, FoodName = "Pasta with meat sauce", CaloryPerGram = 1.69f, PhotoPath = ".\\Images\\Pasta with meatballs.jpg" },
                new Food { Id = 15, FoodName = "Meatballs", CaloryPerGram = 1.49f, PhotoPath = ".\\Images\\Meatballs.jpg" },
                new Food { Id = 16, FoodName = "Turkey chili", CaloryPerGram = 1.59f, PhotoPath = ".\\Images\\Turkey chili.jpg" },
                new Food { Id = 17, FoodName = "Beef burgers", CaloryPerGram = 2.79f, PhotoPath = ".\\Images\\Beef burgers.jpg" },
                new Food { Id = 18, FoodName = "Chicken curry", CaloryPerGram = 1.99f, PhotoPath = ".\\Images\\Chicken curry.jpg" },
                new Food { Id = 19, FoodName = "Spaghetti Bolognese", CaloryPerGram = 1.79f, PhotoPath = ".\\Images\\Spaghetti bolognese.jpg" },
                new Food { Id = 20, FoodName = "Roasted pork loin", CaloryPerGram = 2.39f, PhotoPath = ".\\Images\\Roasted pork loin.jpg" },
                new Food { Id = 21, FoodName = "Grilled Eggplant", CaloryPerGram = 0.25f, PhotoPath = ".\\Images\\Grilled Eggplant.jpg" },
                new Food { Id = 22, FoodName = "Stuffed Zucchini", CaloryPerGram = 0.39f, PhotoPath = ".\\Images\\Stuffed Zucchini.jpg" },
                new Food { Id = 23, FoodName = "Roasted Brussels Sprouts", CaloryPerGram = 0.43f, PhotoPath = ".\\Images\\Roasted brussel sprouts.jpg" },
                new Food { Id = 24, FoodName = "Cauliflower Fried Rice", CaloryPerGram = 0.4f, PhotoPath = ".\\Images\\Fried rice.jpg" },
                new Food { Id = 25, FoodName = "Sautéed Kale", CaloryPerGram = 0.27f, PhotoPath = ".\\Images\\Sautéed Kale.jpg" },
                new Food { Id = 26, FoodName = "Roasted Sweet Potatoes", CaloryPerGram = 0.76f, PhotoPath = ".\\Images\\Roasted sweet potatoes.jpg" },
                new Food { Id = 27, FoodName = "Stir-Fried Bok Choy", CaloryPerGram = 0.12f, PhotoPath = ".\\Images\\Stir-fried bok choy.jpg" },
                new Food { Id = 28, FoodName = "Grilled Asparagus", CaloryPerGram = 0.2f, PhotoPath = ".\\Images\\Grilled Asparagus.jpg" },
                new Food { Id = 29, FoodName = "Roasted Carrots", CaloryPerGram = 0.41f, PhotoPath = ".\\Images\\Roasted Carrots.jpg" },
                new Food { Id = 30, FoodName = "Mushroom Risotto", CaloryPerGram = 0.34f, PhotoPath = ".\\Images\\Mushroom Risotto.jpg" },
                new Food { Id = 31, FoodName = "Steamed broccoli", CaloryPerGram = 0.35f, PhotoPath = ".\\Images\\Steamed broccoli.jpg" },
                new Food { Id = 32, FoodName = "Roasted asparagus", CaloryPerGram = 0.27f, PhotoPath = ".\\Images\\Roasted asparagus.jpg" },
                new Food { Id = 33, FoodName = "Mashed potatoes", CaloryPerGram = 0.86f, PhotoPath = ".\\Images\\Mashed potatoes.jpg" },
                new Food { Id = 34, FoodName = "Garlic green beans", CaloryPerGram = 0.33f, PhotoPath = ".\\Images\\Garlic green beans.jpg" },
                new Food { Id = 35, FoodName = "Grilled zucchini", CaloryPerGram = 0.17f, PhotoPath = ".\\Images\\Grilled zucchini.jpg" },
                new Food { Id = 36, FoodName = "Creamed spinach", CaloryPerGram = 0.69f, PhotoPath = ".\\Images\\Creamed spinach.jpg" },
                new Food { Id = 37, FoodName = "Fried rice", CaloryPerGram = 1.05f, PhotoPath = ".\\Images\\Fried rice.jpg" },
                new Food { Id = 38, FoodName = "Sweet potato fries", CaloryPerGram = 1.3f, PhotoPath = ".\\Images\\Sweet potato fries.jpg" },
                new Food { Id = 39, FoodName = "Baked beans", CaloryPerGram = 0.86f, PhotoPath = ".\\Images\\Bakedbeans.jpg" },
                new Food { Id = 40, FoodName = "Tomato soup", CaloryPerGram = 0.35f, PhotoPath = ".\\Images\\Tomato soup.jpg" },
                new Food { Id = 41, FoodName = "Pumpkin soup", CaloryPerGram = 0.25f, PhotoPath = ".\\Images\\Pumpkin soup.jpg" },
                new Food { Id = 42, FoodName = "Mushroom soup", CaloryPerGram = 0.4f, PhotoPath = ".\\Images\\Mushroom soup.jpg" },
                new Food { Id = 43, FoodName = "Chicken noodle soup", CaloryPerGram = 0.45f, PhotoPath = ".\\Images\\Chicken noodle soup.jpg" },
                new Food { Id = 44, FoodName = "Beef soup", CaloryPerGram = 0.4f, PhotoPath = ".\\Images\\Beef soup.jpg" },
                new Food { Id = 45, FoodName = "Corn soup", CaloryPerGram = 0.35f, PhotoPath = ".\\Images\\Corn soup.jpg" },
                new Food { Id = 46, FoodName = "Minestrone soup", CaloryPerGram = 0.3f, PhotoPath = ".\\Images\\Minestrone soup.jpg" },
                new Food { Id = 47, FoodName = "Vegetable soup", CaloryPerGram = 0.25f, PhotoPath = ".\\Images\\Vegetable soup.jpg" },
                new Food { Id = 48, FoodName = "Clam chowder", CaloryPerGram = 0.5f, PhotoPath = ".\\Images\\Clam chowder.jpg" },
                new Food { Id = 49, FoodName = "Lentil soup", CaloryPerGram = 0.3f, PhotoPath = ".\\Images\\Lentil soup.jpg" },
                new Food { Id = 50, FoodName = "Rice", CaloryPerGram = 3.75f, PhotoPath = ".\\Images\\Rice.jpg" },
                new Food { Id = 51,  FoodName = "Bread", CaloryPerGram = 2.64f, PhotoPath = ".\\Images\\Bread.jpg" },
                new Food { Id = 52, FoodName = "Pasta", CaloryPerGram = 3.38f, PhotoPath = ".\\Images\\Pasta.jpg" },
                new Food { Id = 53, FoodName = "Quinoa", CaloryPerGram = 3.68f, PhotoPath = ".\\Images\\Quinoa.jpg" },
                new Food { Id = 54, FoodName = "Bulgur", CaloryPerGram = 3.33f, PhotoPath = ".\\Images\\Bulgur.jpg" },
                new Food { Id = 55, FoodName = "Couscous", CaloryPerGram = 3.81f, PhotoPath = ".\\Images\\Couscous.jpg" },
                new Food { Id = 56, FoodName = "Oats", CaloryPerGram = 3.37f, PhotoPath = ".\\Images\\Oats.jpg" },
                new Food { Id = 57, FoodName = "Barley", CaloryPerGram = 3.44f, PhotoPath = ".\\Images\\Barley.jpg" },
                new Food { Id = 58, FoodName = "Wheat berries", CaloryPerGram = 3.3f, PhotoPath = ".\\Images\\Wheat berries.jpg" },
                new Food { Id = 59, FoodName = "Wild rice", CaloryPerGram = 3.72f, PhotoPath = ".\\Images\\Wild rice.jpg" },
                new Food { Id = 60, FoodName = "Oatmeal", CaloryPerGram = 0.68f, PhotoPath = ".\\Images\\Oatmeal.jpg" },
                new Food { Id = 61, FoodName = "Scrambled Eggs", CaloryPerGram = 1.34f, PhotoPath = ".\\Images\\Scrambled eggs.jpg" },
                new Food { Id = 62, FoodName = "Bacon", CaloryPerGram = 5.42f, PhotoPath = ".\\Images\\Bacon.jpg" },
                new Food { Id = 63, FoodName = "Sausage", CaloryPerGram = 4.85f, PhotoPath = ".\\Images\\Sausage.jpg" },
                new Food { Id = 64, FoodName = "French Toast", CaloryPerGram = 2.92f, PhotoPath = ".\\Images\\French toast.jpg" },
                new Food { Id = 65, FoodName = "Waffles", CaloryPerGram = 2.86f, PhotoPath = ".\\Images\\Waffles.jpg" },
                new Food { Id = 66, FoodName = "Pancakes", CaloryPerGram = 2.52f, PhotoPath = ".\\Images\\Pancakes.jpg" },
                new Food { Id = 67, FoodName = "Bagel", CaloryPerGram = 2.71f, PhotoPath = ".\\Images\\Bagel.jpg" },
                new Food { Id = 68, FoodName = "Cream Cheese", CaloryPerGram = 3.79f, PhotoPath = ".\\Images\\Cream Cheese.jpg" },
                new Food { Id = 69, FoodName = "Fruit Salad", CaloryPerGram = 0.67f, PhotoPath = ".\\Images\\Bacon.jpg" },
                new Food { Id = 70, FoodName = "Popcorn", CaloryPerGram = 5.85f, PhotoPath = ".\\Images\\Popcorn.jpg" },
                new Food { Id = 71, FoodName = "Trail Mix", CaloryPerGram = 4.2f, PhotoPath = ".\\Images\\Tail mix.jpg" },
                new Food { Id = 72, FoodName = "Energy Bars", CaloryPerGram = 4.0f, PhotoPath = ".\\Images\\Energy Bars.jpg" },
                new Food { Id = 73, FoodName = "Fruit Cups", CaloryPerGram = 0.73f, PhotoPath = ".\\Images\\Fruit cups.jpg" },
                new Food { Id = 74, FoodName = "Yogurt Cups", CaloryPerGram = 0.75f, PhotoPath = ".\\Images\\Yogurt cups.jpg" },
                new Food { Id = 75, FoodName = "Nuts", CaloryPerGram = 6.0f, PhotoPath = ".\\Images\\Nuts.jpg" },
                new Food { Id = 76, FoodName = "Cheese and Crackers", CaloryPerGram = 3.0f, PhotoPath = ".\\Images\\Cheese and Crackers.jpg" },
                new Food { Id = 77, FoodName = "Pretzels", CaloryPerGram = 3.17f, PhotoPath = ".\\Images\\Pretzels.jpg" },
                new Food { Id = 78, FoodName = "Hummus", CaloryPerGram = 1.0f, PhotoPath = ".\\Images\\Hummus.jpg" },
                new Food { Id = 79, FoodName = "Dark Chocolate", CaloryPerGram = 5.0f, PhotoPath = ".\\Images\\Dark chocolate.jpg" },
                new Food { Id = 80, FoodName = "Water", CaloryPerGram = 0, PhotoPath = ".\\Images\\Water.jpg" },
                new Food { Id = 81, FoodName = "Tea", CaloryPerGram = 0.16f, PhotoPath = ".\\Images\\Tea.jpg" },
                new Food { Id = 82, FoodName = "Coffee", CaloryPerGram = 0.1f, PhotoPath = ".\\Images\\Coffee.jpg" },
                new Food { Id = 83, FoodName = "Juice", CaloryPerGram = 0.44f, PhotoPath = ".\\Images\\Juice.jpg" },
                new Food { Id = 84, FoodName = "Milk", CaloryPerGram = 0.67f, PhotoPath = ".\\Images\\Milk.jpg" },
                new Food { Id = 85, FoodName = "Soda", CaloryPerGram = 0.41f, PhotoPath = ".\\Images\\Soda.jpg" },
                new Food { Id = 86, FoodName = "Mineral Water", CaloryPerGram = 0, PhotoPath = ".\\Images\\Mineral Water.jpg" },
                new Food { Id = 87, FoodName = "Turkish Coffee", CaloryPerGram = 0.1f, PhotoPath = ".\\Images\\Turkish coffee.jpg" },
                new Food { Id = 88, FoodName = "Lemonade", CaloryPerGram = 0.4f, PhotoPath = ".\\Images\\Lemonade.jpg" },
                new Food { Id = 89, FoodName = "Smoothie", CaloryPerGram = 0.56f, PhotoPath = ".\\Images\\Smoothie.jpg" },
                new Food { Id = 90, FoodName = "Caesar Salad", CaloryPerGram = 1.13f, PhotoPath = ".\\Images\\Caesar salad.jpg" },
                new Food { Id = 91, FoodName = "Cobb Salad", CaloryPerGram = 1.05f, PhotoPath = ".\\Images\\Cobb salad.jpg" },
                new Food { Id = 92, FoodName = "Greek Salad", CaloryPerGram = 0.96f, PhotoPath = ".\\Images\\Greek salad.jpg" },
                new Food { Id = 93, FoodName = "Caprese Salad", CaloryPerGram = 0.89f, PhotoPath = ".\\Images\\Caprese salad.jpg" },
                new Food { Id = 94, FoodName = "Spinach Salad", CaloryPerGram = 0.81f, PhotoPath = ".\\Images\\Spinach salad.jpg" },
                new Food { Id = 95, FoodName = "Coleslaw", CaloryPerGram = 0.76f, PhotoPath = ".\\Images\\Coleslaw.jpg" },
                new Food { Id = 96, FoodName = "Waldorf Salad", CaloryPerGram = 0.92f, PhotoPath = ".\\Images\\Waldorf salad.jpg" },
                new Food { Id = 97, FoodName = "Beetroot Salad", CaloryPerGram = 0.78f, PhotoPath = ".\\Images\\Beetroot salad.jpg" },
                new Food { Id = 98, FoodName = "Pasta Salad", CaloryPerGram = 0.88f, PhotoPath = ".\\Images\\Pasta Salad.jpg" },
                new Food { Id = 99, FoodName = "Tuna Salad", CaloryPerGram = 0.98f, PhotoPath = ".\\Images\\Tuna salad.jpg" },
                new Food { Id = 100, FoodName = "Chocolate cake", CaloryPerGram = 3.87f, PhotoPath = ".\\Images\\Chocolate Cake.jpg" },
                new Food { Id = 101, FoodName = "Apple pie", CaloryPerGram = 2.8f, PhotoPath = ".\\Images\\Applepie.jpg" },
                new Food { Id = 102, FoodName = "Pumpkin pie", CaloryPerGram = 3.0f, PhotoPath = ".\\Images\\Pumpkin pie.jpg" },
                new Food { Id = 103, FoodName = "Cheesecake", CaloryPerGram = 3.2f, PhotoPath = ".\\Images\\Cheesecake.jpg" },
                new Food { Id = 104, FoodName = "Strawberry shortcake", CaloryPerGram = 2.89f, PhotoPath = ".\\Images\\Strawberry Shortcake.jpg" },
                new Food { Id = 105, FoodName = "Ice cream", CaloryPerGram = 1.5f, PhotoPath = ".\\Images\\Ice Cream.jpg" },
                new Food { Id = 106, FoodName = "Brownie", CaloryPerGram = 3.6f, PhotoPath = ".\\Images\\Brownie.jpg" },
                new Food { Id = 107, FoodName = "Fruit salad", CaloryPerGram = 1.08f, PhotoPath = ".\\Images\\Fruit Salad.jpg" },
                new Food { Id = 108, FoodName = "Banana pudding", CaloryPerGram = 1.83f, PhotoPath = ".\\Images\\Bananapudding.jpg" },
                new Food { Id = 109, FoodName = "Tiramisu", CaloryPerGram = 3.1f, PhotoPath = ".\\Images\\Tiramisu.jpg" },
                new Food { Id = 110, FoodName = "Apple", CaloryPerGram = 0.52f, PhotoPath = ".\\Images\\Apple.jpg" },
                new Food { Id = 111, FoodName = "Banana", CaloryPerGram = 0.89f, PhotoPath = ".\\Images\\Banana.jpg" },
                new Food { Id = 112, FoodName = "Orange", CaloryPerGram = 0.47f, PhotoPath = ".\\Images\\Orange.jpg" },
                new Food { Id = 113, FoodName = "Strawberry", CaloryPerGram = 0.32f, PhotoPath = ".\\Images\\Strawberry.jpg" },
                new Food { Id = 114, FoodName = "Watermelon", CaloryPerGram = 0.3f, PhotoPath = ".\\Images\\Watermelon.jpg" },
                new Food { Id = 115, FoodName = "Grape", CaloryPerGram = 0.69f, PhotoPath = ".\\Images\\Grape.jpg" },
                new Food { Id = 116, FoodName = "Pineapple", CaloryPerGram = 0.5f, PhotoPath = ".\\Images\\Pineapple.jpg" },
                new Food { Id = 117, FoodName = "Kiwi", CaloryPerGram = 0.61f, PhotoPath = ".\\Images\\Kiwi.jpg" },
                new Food { Id = 118, FoodName = "Cherry", CaloryPerGram = 0.5f, PhotoPath = ".\\Images\\Cherry.jpg" },
                new Food { Id = 119, FoodName = "Mango", CaloryPerGram = 0.6f, PhotoPath = ".\\Images\\Mango.jpg" }
            );
            
    }
}
